//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NHibernate.Type;
using NUnit.Framework;

namespace NHibernate.Test.TypesTest
{
	using System.Threading.Tasks;
	public abstract class AbstractDateTimeTypeWithScaleFixtureAsync<TTestType> : AbstractDateTimeTypeFixtureAsync<TTestType> where TTestType : AbstractDateTimeType
	{
		// The timestamp rounding in seeding does not account scale.
		protected override bool RevisionCheck => false;

		//Use an accurency one digit less than the dialect's
		protected override long DateAccuracyInTicks => Math.Min(Dialect.TimestampResolutionInTicks * 10, TimeSpan.TicksPerSecond);


		[Test]
		public async Task LowerDigitsAreIgnoredAsync()
		{
			if (DateAccuracyInTicks == TimeSpan.TicksPerSecond)
				Assert.Ignore("The dialect doesn't support fractional seconds");

			var baseDate = new DateTime(2017, 10, 01, 17, 55, 24, GetTypeKind());
			var entity = new DateTimeClass
			{
				Id = AdditionalDateId,
				Value = baseDate.AddTicks(DateAccuracyInTicks / 10)
			};
			Assert.That(entity.Value, Is.Not.EqualTo(baseDate));

			using (var s = OpenSession())
			using (var t = s.BeginTransaction())
			{
				await (s.SaveAsync(entity));
				await (t.CommitAsync());
			}

			using (var s = OpenSession())
			using (var t = s.BeginTransaction())
			{
				var retrieved = await (s.LoadAsync<DateTimeClass>(AdditionalDateId));
				Assert.That(retrieved.Value, Is.EqualTo(baseDate));
				await (t.CommitAsync());
			}
		}
	}
}
