//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Type;
using NUnit.Framework;

namespace NHibernate.Test.TypesTest
{
	using System.Threading.Tasks;
	/// <summary>
	/// The Unit Tests for the LocalDateTimeType.
	/// </summary>
	[TestFixture]
	public class LocalDateTimeTypeFixtureAsync : AbstractDateTimeTypeFixtureAsync<LocalDateTimeType>
	{
		protected override LocalDateTimeType Type => NHibernateUtil.LocalDateTime;
	}

	[TestFixture]
	public class LocalDateTimeTypeWithScaleFixtureAsync : AbstractDateTimeTypeWithScaleFixtureAsync<LocalDateTimeType>
	{
		protected override LocalDateTimeType Type => (LocalDateTimeType) TypeFactory.GetLocalDateTimeType(ScaleFromDateAccuracyInTicks);
	}

	[TestFixture]
	public class LocalDateTimeNoMsTypeFixtureAsync : AbstractDateTimeNoMsTypeFixtureAsync<LocalDateTimeNoMsType>
	{
		protected override LocalDateTimeNoMsType Type => NHibernateUtil.LocalDateTimeNoMs;
	}
}
