//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NHibernate.Cfg;
using NHibernate.Mapping.ByCode;
using NHibernate.Type;
using NUnit.Framework;

namespace NHibernate.Test.TypesTest
{
	using System.Threading.Tasks;
	[TestFixture]
	public class TimeFixtureAsync : TimeOrDateTypeFixtureBase<TimeClass, TimeType>
	{
		protected override void AddMappingsToModelMapper(ModelMapper mapper)
		{
			mapper.Class<TimeClass>(m =>
			{
				m.Table("bc_time");
				m.Lazy(false);
				m.Id(p => p.Id, p => p.Generator(Generators.Native));
				m.Property(p => p.TimeValue,
					p => p.Type<TimeType>()
				);
				m.Property(p => p.TimeWithScale,
					p =>
					{
						p.Type<TimeType>();
						p.Scale(ScaleFromDateAccuracyInTicks);
					}
				);
			});
		}

		[Test]
		public async Task SavingAndRetrievingAsync()
		{
			var ticks = DateTime.Parse("23:59:59");

			var entity =
				new TimeClass
				{
					TimeValue = ticks
				};

			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				await (s.SaveAsync(entity));
				await (tx.CommitAsync());
			}

			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				var entityReturned = await (s.CreateQuery("from TimeClass").UniqueResultAsync<TimeClass>());

				Assert.That(entityReturned.TimeValue.TimeOfDay, Is.EqualTo(ticks.TimeOfDay));
				Assert.That(ticks.Hour, Is.EqualTo(entityReturned.TimeValue.Hour));
				Assert.That(ticks.Minute, Is.EqualTo(entityReturned.TimeValue.Minute));
				Assert.That(ticks.Second, Is.EqualTo(entityReturned.TimeValue.Second));
				await (tx.CommitAsync());
			}
		}

		[Test]
		public async Task LowerDigitsAreIgnoredAsync()
		{
			if (DateAccuracyInTicks == TimeSpan.TicksPerSecond)
				Assert.Ignore("The dialect doesn't support fractional seconds");

			var baseTime = new DateTime(1990, 01, 01, 17, 55, 24);
			var entity = new TimeClass
			{
				TimeWithScale = baseTime.Add(TimeSpan.FromTicks(DateAccuracyInTicks / 10))
			};
			Assert.That(entity.TimeWithScale, Is.Not.EqualTo(baseTime));

			int id;
			using (var s = OpenSession())
			using (var t = s.BeginTransaction())
			{
				await (s.SaveAsync(entity));
				id = entity.Id;
				await (t.CommitAsync());
			}

			using (var s = OpenSession())
			using (var t = s.BeginTransaction())
			{
				var retrieved = await (s.LoadAsync<TimeClass>(id));
				Assert.That(retrieved.TimeWithScale.TimeOfDay, Is.EqualTo(baseTime.TimeOfDay));
				await (t.CommitAsync());
			}
		}
	}
}
