//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Type;
using NUnit.Framework;

namespace NHibernate.Test.TypesTest
{
	using System.Threading.Tasks;
	/// <summary>
	/// The Unit Tests for the UtcDateTimeType.
	/// </summary>
	[TestFixture]
	public class UtcDateTimeTypeFixtureAsync : AbstractDateTimeTypeFixtureAsync<UtcDateTimeType>
	{
		protected override UtcDateTimeType Type => NHibernateUtil.UtcDateTime;
	}

	[TestFixture]
	public class UtcDateTimeTypeWithScaleFixtureAsync : AbstractDateTimeTypeWithScaleFixtureAsync<UtcDateTimeType>
	{
		protected override UtcDateTimeType Type => (UtcDateTimeType) TypeFactory.GetUtcDateTimeType(ScaleFromDateAccuracyInTicks);
	}

	[TestFixture]
	public class UtcDateTimeNoMsTypeFixtureAsync : AbstractDateTimeNoMsTypeFixtureAsync<UtcDateTimeNoMsType>
	{
		protected override UtcDateTimeNoMsType Type => NHibernateUtil.UtcDateTimeNoMs;
	}
}
