//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Linq;
using NHibernate.Cfg;
using NHibernate.Linq;
using NUnit.Framework;

namespace NHibernate.Test.Linq
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class QueryCacheableTestsAsync : LinqTestCase
	{
		protected override void Configure(Configuration cfg)
		{
			cfg.SetProperty(Environment.UseQueryCache, "true");
			cfg.SetProperty(Environment.GenerateStatistics, "true");
			base.Configure(cfg);
		}

		[Test]
		public async Task QueryIsCacheableAsync()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			var x = await ((from c in db.Customers
					 select c)
				.WithOptions(QueryCache.Enabled)
				.ToListAsync());

			var x2 = await ((from c in db.Customers
					  select c)
				.WithOptions(QueryCache.Enabled)
				.ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(1), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(1), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(1), "Unexpected cache hit count");
		}

		[Test]
		public async Task QueryIsCacheable2Async()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			var x = await ((from c in db.Customers
					 select c)
				.WithOptions(QueryCache.Enabled)
				.ToListAsync());

			var x2 = await ((from c in db.Customers
					  select c).ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(2), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(1), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(0), "Unexpected cache hit count");
		}

		[Test]
		public async Task QueryIsCacheable3Async()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			var x = await ((from c in db.Customers.WithOptions(QueryCache.Enabled)
					 select c).ToListAsync());

			var x2 = await ((from c in db.Customers
					  select c).ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(2), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(1), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(0), "Unexpected cache hit count");
		}

		[Test]
		public async Task QueryIsCacheableWithRegionAsync()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			var x = await ((from c in db.Customers
					 select c)
				.WithOptions(QueryCache.Enabled.InRegion("test"))
				.ToListAsync());

			var x2 = await ((from c in db.Customers
					  select c)
				.WithOptions(QueryCache.Enabled.InRegion("test"))
				.ToListAsync());

			var x3 = await ((from c in db.Customers
					  select c)
				.WithOptions(QueryCache.Enabled.InRegion("other"))
				.ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(2), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(2), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(1), "Unexpected cache hit count");
		}

		[Test]
		public async Task CacheableBeforeOtherClausesAsync()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			await (db.Customers
				.WithOptions(QueryCache.Enabled)
				.Where(c => c.ContactName != c.CompanyName).Take(1).ToListAsync());
			await (db.Customers.Where(c => c.ContactName != c.CompanyName).Take(1).ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(2), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(1), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(0), "Unexpected cache hit count");
		}

		[Test]
		public async Task CacheableRegionBeforeOtherClausesAsync()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			await (db.Customers
				.WithOptions(QueryCache.Enabled.InRegion("test"))
				.Where(c => c.ContactName != c.CompanyName).Take(1)
				.ToListAsync());
			await (db.Customers
				.WithOptions(QueryCache.Enabled.InRegion("test"))
				.Where(c => c.ContactName != c.CompanyName).Take(1)
				.ToListAsync());
			await (db.Customers
			    .WithOptions(QueryCache.Enabled.InRegion("other"))
				.Where(c => c.ContactName != c.CompanyName).Take(1)
				.ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(2), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(2), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(1), "Unexpected cache hit count");
		}

		[Test]
		public async Task CacheableRegionSwitchedAsync()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			await (db.Customers
				.Where(c => c.ContactName != c.CompanyName).Take(1)
				.WithOptions(QueryCache.Enabled.InRegion("test"))
				.ToListAsync());
			await (db.Customers
				.Where(c => c.ContactName != c.CompanyName).Take(1)
			    .WithOptions(QueryCache.Enabled.InRegion("test"))
				.ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(1), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(1), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(1), "Unexpected cache hit count");
		}

		[Test]
		public async Task GroupByQueryIsCacheableAsync()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			var c = await (db
				.Customers
				.GroupBy(x => x.Address.Country)
				.Select(x => x.Key)
				.WithOptions(QueryCache.Enabled)
				.ToListAsync());

			c = await (db
				.Customers
				.GroupBy(x => x.Address.Country)
				.Select(x => x.Key)
				.ToListAsync());

			c = await (db
				.Customers
				.GroupBy(x => x.Address.Country)
				.Select(x => x.Key)
				.WithOptions(QueryCache.Enabled)
				.ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(2), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(1), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(1), "Unexpected cache hit count");
		}

		[Test]
		public async Task GroupByQueryIsCacheable2Async()
		{
			Sfi.Statistics.Clear();
			await (Sfi.QueryCache.ClearAsync(CancellationToken.None));

			var c = await (db
				.Customers
				.WithOptions(QueryCache.Enabled)
				.GroupBy(x => x.Address.Country)
				.Select(x => x.Key)
				.ToListAsync());

			c = await (db
				.Customers
				.GroupBy(x => x.Address.Country)
				.Select(x => x.Key)
				.ToListAsync());

			c = await (db
				.Customers
				.WithOptions(QueryCache.Enabled)
				.GroupBy(x => x.Address.Country)
				.Select(x => x.Key)
				.ToListAsync());

			Assert.That(Sfi.Statistics.QueryExecutionCount, Is.EqualTo(2), "Unexpected execution count");
			Assert.That(Sfi.Statistics.QueryCachePutCount, Is.EqualTo(1), "Unexpected cache put count");
			Assert.That(Sfi.Statistics.QueryCacheHitCount, Is.EqualTo(1), "Unexpected cache hit count");
		}
	}
}
